/*
    MapReduce library

    Copyright (C) 2009 Craig Henderson.
    cdm.henderson@gmail.com

    Use, modification and distribution is subject to the
    Boost Software License, Version 1.0 - August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

#ifndef MAPREDUCE_SEQUENTIAL_SCHEDULE_HPP
#define MAPREDUCE_SEQUENTIAL_SCHEDULE_HPP

namespace mapreduce {

namespace schedule_policy {

namespace detail {

struct null_lock
{
    void lock(void)   { }
    void unlock(void) { }
};

}   // namespace detail


template<typename Job>
class sequential
{
  public:
    void operator()(Job &job, results &result)
    {
        using namespace boost::posix_time;
        ptime start_time(microsec_clock::universal_time());

        // Map Tasks
        void *key = 0;
        detail::null_lock nolock;
        while (job.get_next_map_key(key)  &&  job.run_map_task(key, result, nolock))
            ;
        result.map_runtime = microsec_clock::universal_time() - start_time;

        // Intermediate results shuffle
        start_time = microsec_clock::universal_time();
        for (unsigned partition=0; partition<job.number_of_partitions(); ++partition)
            job.run_intermediate_results_shuffle(partition);
        result.shuffle_runtime = microsec_clock::universal_time() - start_time;

        // Reduce Tasks
        start_time = microsec_clock::universal_time();
        for (unsigned partition=0; partition<job.number_of_partitions(); ++partition)
            job.run_reduce_task(partition, result);
        result.reduce_runtime = microsec_clock::universal_time() - start_time;

        result.counters.actual_map_tasks    = 1;
        result.counters.actual_reduce_tasks = 1;
        result.counters.num_result_files    = job.number_of_partitions();
    }
};

}   // namespace schedule_policy

}   // namespace mapreduce 

#endif  // MAPREDUCE_SEQUENTIAL_SCHEDULE_HPP
